### ISSUE TITLE
Fix for 1.6 for CBTHeat and CBTPiloting

### ISSUE THREAD

**Issue by Red1812** [BattletechModders/CBTBehaviors#3]
Hello,
I made a fix for CBTHeat and CBTPiloting to work with 1.6. I tested it on a mission and everything went fine. I attached the dll and cs files.
[CBTPiloting_CBTHeat_1.6fix.zip](https://github.com/BattletechModders/CBTBehaviors/files/3254363/CBTPiloting_CBTHeat_1.6fix.zip)
Since I'm barely level noob coding wise I hope you can have a look and make sure what I did is indeed correct.

**Comment by IceRaptor** [comment]
Can you elaborate on the issue you experienced? What went wrong? 

And how did you fix it?

**Comment by Red1812** [comment]
Before "fixing" CBTHeat I couldn't finish a turn so I download the source, opened it in Visual Studio and fixed the issue reported by VS. Then I went on doing the same with CBTPiloting.
Also I realized I put the wrong dll in the previous archive, sorry.
[Mods.zip](https://github.com/BattletechModders/CBTBehaviors/files/3254462/Mods.zip)
That being said I also had to fix my mod (https://github.com/Red1812/PermanentEvasion) so I might have been a bit carried away, hence the post here.

**Comment by IceRaptor** [comment]
Ah, gotcha - thank you. CBTBehaviors is already updated for 1.6 though, so it should be ready to use as is. 

Cheers!

**Comment by Red1812** [comment]
Ah my bad I must have missed the update, sorry :)

**Comment by tezzy808** [comment]
Hi IceRaptor, Red1812,

Apologies if I'm hijacking this thread (I didn't want to unnecessarily create another "issue") but I downloaded CBTBehaviors release 0.1.0 and the zip file doesn't include the _CBTBehaviors.dll_ file.  I looked around but couldn't find it and when I saw your (Red1812) _mods.zip_ I thought I might find it in there.

Are you able to provide a link to _CBTBehaviors.dll_ or point me in the right direction?
Or do I even need _CBTBehaviors.dll_?  (It's listed in _mod.json_ so I assume I do.)

And apologies if this is not what the "Issues" tab is for.  I looked on Reddit/Paradox/Steam forums but didn't find any info related to this.

Thanks again!

**Comment by IceRaptor** [comment]
Sorry about that folks. I forgot to upload the mod bundle. You can find a 0.1.0 zip (with DLL and mod.json) in the releases tab at https://github.com/BattletechModders/CBTBehaviors/releases/tag/REL_0.1.0. 

This was a port from McFistyBun's code, and hasn't been fully tested yet. The RogueTech crew is working through that, but be aware there may be issues. Please let me know if there are any.

Feel free to re-open if you have problems. Cheers!
